<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="ZahlungsverbindungChangeService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  targetNamespace="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungchange:v0"
                  xmlns:tns="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungchange:v0"
                  xmlns:pa="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungchange:v0:schema"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v_1_0"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungchange:v0:schema" schemaLocation="schema/ZahlungsverbindungChangeService.xsd"/>
            <xsd:import namespace="urn:com:adcubum:syrius:api:common:faults:v_1_0" schemaLocation="../../../../../common/faults/v_1_0/faults.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ZahlungsverbindungChangeRequestMessage">
        <wsdl:part name="Request" element="pa:zahlungsverbindungChangeRequest"/>
    </wsdl:message>
    <wsdl:message name="ZahlungsverbindungChangeResponseMessage">
        <wsdl:part name="Response" element="pa:zahlungsverbindungChangeResponse"/>
    </wsdl:message>
    <wsdl:message name="ApiFault">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>
    <wsdl:portType name="ZahlungsverbindungChangeServicePortType">
        <wsdl:operation name="changeBankZahlungsverbindung">
            <wsdl:documentation>Ändert ein Zahlungsverbindung-Objekt.</wsdl:documentation>
            <wsdl:input name="ZahlungsverbindungChangeRequest" message="tns:ZahlungsverbindungChangeRequestMessage"/>
            <wsdl:output name="ZahlungsverbindungChangeResponse" message="tns:ZahlungsverbindungChangeResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ZahlungsverbindungChangeServiceBinding" type="tns:ZahlungsverbindungChangeServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="changeBankZahlungsverbindung">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="ZahlungsverbindungChangeRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ZahlungsverbindungChangeResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ZahlungsverbindungChangeService_v0">
        <wsdl:port name="ZahlungsverbindungChangeService" binding="tns:ZahlungsverbindungChangeServiceBinding">
            <soap:address location="https://example.com/ZahlungsverbindungChangeService_v0"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>