<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="ZahlungsverbindungCreateService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  targetNamespace="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungcreate:v0"
                  xmlns:tns="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungcreate:v0"
                  xmlns:pa="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungcreate:v0:schema"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v_1_0"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:com:adcubum:syrius:api:partnermgmt:partnerdatenverw:process:zahlungsverbindungcreate:v0:schema" schemaLocation="schema/ZahlungsverbindungCreateService.xsd"/>
            <xsd:import namespace="urn:com:adcubum:syrius:api:common:faults:v_1_0" schemaLocation="../../../../../common/faults/v_1_0/faults.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ZahlungsverbindungCreateRequestMessage">
        <wsdl:part name="Request" element="pa:zahlungsverbindungCreateRequest"/>
    </wsdl:message>
    <wsdl:message name="ZahlungsverbindungCreateResponseMessage">
        <wsdl:part name="Response" element="pa:zahlungsverbindungCreateResponse"/>
    </wsdl:message>
    <wsdl:message name="ApiFault">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>
    <wsdl:portType name="ZahlungsverbindungCreateServicePortType">
        <wsdl:operation name="createBankZahlungsverbindung">
            <wsdl:documentation>Erstellt eine neue Zahlungsverbindung-Objekt.</wsdl:documentation>
            <wsdl:input name="ZahlungsverbindungCreateRequest" message="tns:ZahlungsverbindungCreateRequestMessage"/>
            <wsdl:output name="ZahlungsverbindungCreateResponse" message="tns:ZahlungsverbindungCreateResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ZahlungsverbindungCreateServiceBinding" type="tns:ZahlungsverbindungCreateServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="createBankZahlungsverbindung">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="ZahlungsverbindungCreateRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ZahlungsverbindungCreateResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ZahlungsverbindungCreateService_v0">
        <wsdl:port name="ZahlungsverbindungCreateService" binding="tns:ZahlungsverbindungCreateServiceBinding">
            <soap:address location="https://example.com/ZahlungsverbindungCreateService_v0"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
